### ISSUE TITLE
Compatibility with kotlin 1.3.60+

### ISSUE THREAD

**Issue by pecanw** [yshrsmz/kgql#28]
After upgrading project to kotlin 1.3.60 (or 1.3.61) I get following error:

```
> Task :data:compileKotlinIos FAILED
w: skipping /Users/runner/.gradle/caches/modules-2/files-2.1/com.codingfeline.kgql/core-iosX64/0.4.0/28cedc1755fff9a22add151c04aa3cf06afbd2da/kgql-core.klib. The abi versions don't match. Expected '[17]', found '14'
w: The compiler versions don't match either. Expected '[]', found '1.3.50-release-11850'
e: Could not find "/Users/runner/.gradle/caches/modules-2/files-2.1/com.codingfeline.kgql/core-iosX64/0.4.0/28cedc1755fff9a22add151c04aa3cf06afbd2da/kgql-core.klib" in [/Users/runner/runners/2.160.1/work/1/s, /Users/runner/.konan/klib, /Users/runner/.konan/kotlin-native-macos-1.3.61/klib/common, /Users/runner/.konan/kotlin-native-macos-1.3.61/klib/platform/ios_x64].
```

This is (probably) caused by the fact that the current version of kgql is compiled with kotlin 1.3.50.

Can you please release a new version compiled with kotlin 1.3.60 or 1.3.61?

**Comment by yshrsmz** [comment]
v0.4.2 is released with Kotlin 1.3.61 compatibility.
Let me know if you have any problem

**Comment by pecanw** [comment]
Have you published it to a repository? I cannot see it on the [Maven repository](https://mvnrepository.com/artifact/gradle.plugin.com.codingfeline.kgql/kgql-gradle-plugin):  latest version is 0.4.0.

**Comment by yshrsmz** [comment]
@pecanw 
hmm, I have never uploaded to that maven repository.

these are the place I've been managing
https://plugins.gradle.org/plugin/com.codingfeline.kgql
https://dl.bintray.com/yshrsmz/kgql

**Comment by pecanw** [comment]
Yes I can see I have it configured correctly (to take from https://dl.bintray.com/yshrsmz/kgql), but the build fails. I'll try to clean and re-build...

**Comment by pecanw** [comment]
After rebuild it is working fine (at least on Win/Android). I'll check on Mac in a while and let you know...
