### ISSUE TITLE
Get rid of KT-27059 workaround

### ISSUE THREAD

**Issue by micHar** [yshrsmz/kgql#32]
Not really an issue, but wanted to tell you, that I was looking at your project to understand how to marry the codegen (kotlinpoet) jvm-only module with a multiplatform module and found out, that the workaround for https://youtrack.jetbrains.com/issue/KT-27059 is probably no longer necessary. At least for me gradle 6.5 / gradle plugin 1.4.21 it works without the hack, meaning that I can build my project just fine by referencing `implementation(project(":my-multiplatform-module"))` in the dependencies block of my jvm-only codegen module. Also I use build.gradle.kts but that shouldn't change anything, I think.

**Comment by yshrsmz** [comment]
Thanks, I've just removed the workaround!
